### ISSUE TITLE
Github auth plugin  - KeyError: 'access_token'

### ISSUE THREAD

**Issue by kallisti5** [buildbot/buildbot#4137]
When you click login, you get an internal error from buildbot and the following message:

buildbot-master 1.1.2
```
buildbot_1     | 2018-06-07 02:49:43+0000 [-] While rendering resource:
buildbot_1     | 	Traceback (most recent call last):
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
buildbot_1     | 	    self._startRunCallbacks(fail)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
buildbot_1     | 	    self._runCallbacks()
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
buildbot_1     | 	    current.result = callback(current.result, *args, **kw)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
buildbot_1     | 	    _inlineCallbacks(r, g, deferred)
buildbot_1     | 	--- <exception caught here> ---
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
buildbot_1     | 	    result = result.throwExceptionIntoGenerator(g)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
buildbot_1     | 	    return g.throw(self.type, self.value, self.tb)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/www/oauth2.py", line 63, in renderLogin
buildbot_1     | 	    details = yield self.auth.verifyCode(code)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
buildbot_1     | 	    result = inContext.theWork()
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
buildbot_1     | 	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
buildbot_1     | 	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
buildbot_1     | 	    return func(*args,**kw)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/www/oauth2.py", line 172, in thd
buildbot_1     | 	    session = self.createSessionFromToken(content)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/www/oauth2.py", line 127, in createSessionFromToken
buildbot_1     | 	    s.params = {'access_token': token['access_token']}
buildbot_1     | 	exceptions.KeyError: 'access_token'
```

github config here:
https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg#L500

Installed here:
https://build.haiku-os.org/buildbot

**Comment by tardyp** [comment]
you can't use util.Secret for GithubAuth yet (patch welcome!)

**Comment by kallisti5** [comment]
Hm.. is there a way to convert util.Secret to a string format GithubAuth will accept?

**Comment by tardyp** [comment]
I think the best way is to convince GithubAuth to accept secret. This is not very complicated.

You can see example on how to render secrets here:
https://github.com/buildbot/buildbot/pull/3871/files#diff-97451cd9a8625b0148fe163ce21503a6R207

**Comment by kallisti5** [comment]
ah. I just saw the ```user_key, api_token = yield self.renderSecrets(user_key, api_token)``` stuff.  I'll take a crack at it.

**Comment by kallisti5** [comment]
hm.. I thought I had it, but getting other odd errors:
https://github.com/kallisti5/buildbot/commit/423c1191483f70721d1abd4220345e6a7cda3b98

```
2018-06-07 15:13:34+0000 [_GenericHTTPChannelProtocol,121,172.20.0.11] While rendering resource:
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 60, in render_GET
	    return self.asyncRenderHelper(request, self.renderIndex)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/resource.py", line 67, in asyncRenderHelper
	    d = _callable(request)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 159, in renderIndex
	    tpl = tpl.render(configjson=json.dumps(config, default=toJson),
	  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
	    sort_keys=sort_keys, **kw).encode(obj)
	  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
	    chunks = self.iterencode(o, _one_shot=True)
	  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
	    return _iterencode(o, 0)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 145, in toJson
	    obj = IConfigured(obj).getConfigDict()
	  File "/usr/lib/python2.7/site-packages/buildbot/www/oauth2.py", line 107, in getConfigDict
	    autologin=self.autologin
	exceptions.AttributeError: 'GitHubAuth' object has no attribute 'autologin'
```

**Comment by tardyp** [comment]
>ah. I just saw the user_key, api_token = yield self.renderSecrets(user_key, api_token) stuff. I'll take a crack at it.

no, that snippet is only if you are in a BuildBotService class I don't think that is the case, you need the other snippet:

```
      p = Properties()
      p.master = self.master
      password = yield p.render(password)
```

**Comment by kallisti5** [comment]
Still no love.. same error.
https://github.com/kallisti5/buildbot/commit/05b49b506dfcfdd652db4d82155d70297a92a943

```
2018-06-07 16:45:35+0000 [_GenericHTTPChannelProtocol,10,172.20.0.11] While rendering resource:
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 60, in render_GET
	    return self.asyncRenderHelper(request, self.renderIndex)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/resource.py", line 67, in asyncRenderHelper
	    d = _callable(request)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 159, in renderIndex
	    tpl = tpl.render(configjson=json.dumps(config, default=toJson),
	  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
	    sort_keys=sort_keys, **kw).encode(obj)
	  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
	    chunks = self.iterencode(o, _one_shot=True)
	  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
	    return _iterencode(o, 0)
	  File "/usr/lib/python2.7/site-packages/buildbot/www/config.py", line 145, in toJson
	    obj = IConfigured(obj).getConfigDict()
	  File "/usr/lib/python2.7/site-packages/buildbot/www/oauth2.py", line 109, in getConfigDict
	    autologin=self.autologin
	exceptions.AttributeError: 'GitHubAuth' object has no attribute 'autologin'
```

**Comment by kszucs** [comment]
I'm facing the same issue, fails with both 2.0.1 and 2.1.0, it was working with 2.0.1 but now I can't find a working version (tested from 1.8.1..2.1.0) - the configuration has not been changed:

```python
AUTH = util.GitHubAuth(
    clientId=GITHUB['client_id'],
    clientSecret=GITHUB['client_secret'],
    apiVersion=4,
    getTeamsMembership=True
)
```

ERROR:
```
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/www/oauth2.py", line 168, in thd
            session = self.createSessionFromToken(content)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/www/oauth2.py", line 123, in createSessionFromToken
            s.params = {'access_token': token['access_token']}
        builtins.KeyError: 'access_token'
```

**Comment by kszucs** [comment]
@tardyp this was caused by wrong credentials. Buildbot should log the error returned from the API:

```py
{'error': 'incorrect_client_credentials', 'error_description': 'The client_id and/or clien
t_secret passed are incorrect.', 'error_uri': 'https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oa
uth-app-access-token-request-errors/#incorrect-client-credentials'}
```

**Comment by yan12125** [comment]
> you can't use util.Secret for GithubAuth yet (patch welcome!)

Looks like this this feature will be available in the next buildbot version. https://github.com/buildbot/buildbot/pull/4644
