### ISSUE TITLE
buildbot try fails for files containing non utf-8 characters

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#5933]
buildbot try fails for files containing non utf-8 characters, i.e. different encoding.

e.g.:
```
[~]$buildbot try --connect=pb --master=master-name:1234 --username=buildbot_try --passwd=test --diff=testfile.patch --repository=''
using 'pb' connect method
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.6/site-packages/buildbot/util/eventual.py", line 48, in _turn
    cb(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 937, in trapSystemExit
    why.trap(SystemExit)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 460, in trap
    self.raiseException()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 917, in <lambda>
    d.addCallback(lambda res: self.createJob())
  File "/usr/local/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 582, in createJob
    diff = f.read()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 177: invalid continuation byte

[~]$cat testfile.patch
print("Ïðîâåðêà")
```

**Comment by aj062** [comment]
At https://github.com/buildbot/buildbot/blob/master/master/buildbot/clients/tryclient.py#L581, patch file is being read as string, instead it should be opened in "rb" mode, so as to read the file as bytes.

However, that alone doesn't completely fix the problem, and the code fails at subsequent step with the error: `(unable to obtain traceback): 'bytes' object has no attribute '__module__'`

**Comment by aj062** [comment]
@tardyp @p12tic 
A similar issue was fixed in https://github.com/buildbot/buildbot/pull/5827/files

**Comment by aj062** [comment]
This is a serious regression from older buildbot versions. I believe this was working fine with Python 2 in buildbot 1.8.2
