### PR TITLE
fix tests if txrequests is not present

### LINKED ISSUE #5215: httpclientservice unit tests are failing when txrequests is not available
When running the unit tests without txrequests installed:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 236, in setUp
    httpclientservice.HTTPClientService.getService(self.parent, 'http://foo',
builtins.AttributeError: 'HTTPClientServiceTestTReqNoEncoding' object has no attribute 'parent'

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTReqNoEncoding.test_post_raw
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTReqNoEncoding.test_post_rawlist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 54, in setUp
    raise unittest.SkipTest('this test requires txrequests and treq')
twisted.trial.unittest.SkipTest: this test requires txrequests and treq

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequest.test_post_headers
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequest.test_post_headers
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 134, in setUp
    httpclientservice.HTTPClientService.getService(self.parent, 'http://foo',
builtins.AttributeError: 'HTTPClientServiceTestTxRequestNoEncoding' object has no attribute 'parent'

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_raw
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
```

These tests should be skipped. In fact, they were skipped with version 2.6.0 but they are failing with 2.7.0.

This seems caused by #5191.

### PR DESCRIPTION
**Pull request by tardyp**
fixes #5215

### CODE REVIEW

**Comment by rjarry** [comment]
awesome, thanks

**Comment by rjarry** [comment]
By the way @tardyp, looking at your patch, I found other similar issues introduced by #5191.

Could you also include these in your fix?

```diff
diff --git a/master/buildbot/test/unit/test_process_buildrequestdistributor.py b/master/buildbot/test/unit/test_process
index 0bcd262f40f6..2582faf2e367 100644
--- a/master/buildbot/test/unit/test_process_buildrequestdistributor.py
+++ b/master/buildbot/test/unit/test_process_buildrequestdistributor.py
@@ -367,7 +367,7 @@ class TestMaybeStartBuilds(TestBRDBase):
 
     @defer.inlineCallbacks
     def setUp(self):
-        super().setUp()
+        yield super().setUp()
 
         self.startedBuilds = []
 
diff --git a/master/buildbot/test/unit/test_scripts_cleanupdb.py b/master/buildbot/test/unit/test_scripts_cleanupdb.py
index 303c76ccbfad..61658a4aee42 100644
--- a/master/buildbot/test/unit/test_scripts_cleanupdb.py
+++ b/master/buildbot/test/unit/test_scripts_cleanupdb.py
@@ -134,7 +134,7 @@ class TestCleanupDbRealDb(db.RealDatabaseWithConnectorMixin, TestCleanupDb):
 
     @defer.inlineCallbacks
     def setUp(self):
-        super().setUp()
+        yield super().setUp()
 
         table_names = [
             'logs', 'logchunks', 'steps', 'builds', 'builders',
```

**Comment by tardyp** [comment]
done

**Comment by rjarry** [comment]
Thanks, could you change the title of the commit too? Maybe something like:

```
tests: add missing yields in @inlineCallbacks methods

Fixes: #5215
Fixes: 61b044f924e9 (" - use builderid as a foreign key instead of using buildername for the table buildrequests  - addbuilset take a list of buildersID  - check signatures for the BaseScheduler?'s addBuildsetForXxx methods")
Fixes: c20481e69e0c ("test: Fix tests to wait for DB shutdown")
Fixes: fb4c782daf7e ("test: Use @defer.inlineCallbacks in httpclientservice tests")
```

**Comment by tardyp** [comment]
done

**Comment by rjarry** [comment]
Thanks @tardyp
