### ISSUE TITLE
httpclientservice unit tests are failing when txrequests is not available

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#5215]
When running the unit tests without txrequests installed:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 236, in setUp
    httpclientservice.HTTPClientService.getService(self.parent, 'http://foo',
builtins.AttributeError: 'HTTPClientServiceTestTReqNoEncoding' object has no attribute 'parent'

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTReqNoEncoding.test_post_raw
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTReqNoEncoding.test_post_rawlist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 54, in setUp
    raise unittest.SkipTest('this test requires txrequests and treq')
twisted.trial.unittest.SkipTest: this test requires txrequests and treq

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequest.test_post_headers
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequest.test_post_headers
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.7/dist-packages/buildbot/test/unit/test_util_httpclientservice.py", line 134, in setUp
    httpclientservice.HTTPClientService.getService(self.parent, 'http://foo',
builtins.AttributeError: 'HTTPClientServiceTestTxRequestNoEncoding' object has no attribute 'parent'

buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_raw
buildbot.test.unit.test_util_httpclientservice.HTTPClientServiceTestTxRequestNoEncoding.test_post_rawlist
```

These tests should be skipped. In fact, they were skipped with version 2.6.0 but they are failing with 2.7.0.

This seems caused by #5191.
