### ISSUE TITLE
 error while parsing config file: 'list' object has no attribute 'items' (traceback in logfile)

### ISSUE THREAD

**Issue by aliceinwire** [buildbot/buildbot#3334]
this was working on buildbot-0.9.7

$ buildbot checkconfig master.cfg
--- <exception caught here> ---
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/buildbot/config.py", line 137, in loadConfigDict
    execfile(filename, localDict)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/python/compat.py", line 261, in execfile
    exec(code, globals, locals)
  File "/home/travis/build/gentoo/Gentoo_kernelCI/buildbot/master/master.cfg", line 305, in <module>
    c['www']['auth'] = util.UserPasswordAuth(usernames_passwords)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/buildbot/www/auth.py", line 174, in __init__
    for user, password in users.items():
exceptions.AttributeError: 'list' object has no attribute 'items'

Configuration Errors:
  error while parsing config file: 'list' object has no attribute 'items' (traceback in logfile)

regression in commit d3df5eddaf3bfaa47c0c0925b1f28fbb5380f6bf

**Comment by Frodox** [comment]
it would be cool to provide part of you `master.cfg` anyway :)

**Comment by tardyp** [comment]
fixed via #3335

**Comment by aliceinwire** [comment]
@Frodox https://github.com/gentoo/Gentoo_kernelCI
